export const mockInventory = [
  // Flooring
  {
    id: "F-001",
    name: "3x6 Matte White Subway Tile",
    category: "Flooring",
    price: 0.15,
    unit: "tile",
    vendor: "Home Depot",
    sku: "HD-TILE-01",
    rating: 4.8,
  },
  {
    id: "F-002",
    name: "Oak Hardwood Flooring (Natural)",
    category: "Flooring",
    price: 4.5,
    unit: "sqft",
    vendor: "Lowe's",
    sku: "LW-WOOD-02",
    rating: 4.6,
  },
  {
    id: "F-003",
    name: "Grey Slate Floor Tile (12x24)",
    category: "Flooring",
    price: 2.99,
    unit: "sqft",
    vendor: "Home Depot",
    sku: "HD-SLATE-03",
    rating: 4.7,
  },
  {
    id: "F-004",
    name: "Luxury Vinyl Plank (Barnwood)",
    category: "Flooring",
    price: 3.2,
    unit: "sqft",
    vendor: "Lowe's",
    sku: "LW-LVP-04",
    rating: 4.5,
  },
  {
    id: "F-005",
    name: "Mosaic Penny Tile (Black)",
    category: "Flooring",
    price: 12.0,
    unit: "sheet",
    vendor: "Home Depot",
    sku: "HD-MOS-05",
    rating: 4.9,
  },

  // Plumbing
  {
    id: "P-101",
    name: "Japanese Style Soaking Tub (Acrylic)",
    category: "Plumbing",
    price: 950.0,
    unit: "item",
    vendor: "Home Depot",
    sku: "HD-TUB-101",
    rating: 4.2,
  },
  {
    id: "P-102",
    name: "Brushed Nickel Bathroom Faucet",
    category: "Plumbing",
    price: 89.0,
    unit: "item",
    vendor: "Lowe's",
    sku: "LW-FAUC-102",
    rating: 4.5,
  },
  {
    id: "P-103",
    name: "PEX Pipe 1/2 inch (100ft coil)",
    category: "Plumbing",
    price: 35.0,
    unit: "roll",
    vendor: "Home Depot",
    sku: "HD-PEX-103",
    rating: 4.9,
  },
  {
    id: "P-104",
    name: "Dual Flush Elongated Toilet",
    category: "Plumbing",
    price: 199.0,
    unit: "item",
    vendor: "Home Depot",
    sku: "HD-TOI-104",
    rating: 4.6,
  },
  {
    id: "P-105",
    name: "Rain Shower Head (Matte Black)",
    category: "Plumbing",
    price: 120.0,
    unit: "item",
    vendor: "Lowe's",
    sku: "LW-SHOW-105",
    rating: 4.7,
  },

  // Lumber
  {
    id: "L-201",
    name: "Walnut Veneer Plywood (4x8 sheet)",
    category: "Lumber",
    price: 115.0,
    unit: "sheet",
    vendor: "Home Depot",
    sku: "HD-PLY-201",
    rating: 4.7,
  },
  {
    id: "L-202",
    name: "2x4x8 Kiln Dried Stud",
    category: "Lumber",
    price: 3.5,
    unit: "item",
    vendor: "Lowe's",
    sku: "LW-STUD-202",
    rating: 4.4,
  },
  {
    id: "L-203",
    name: "Pressure Treated Decking Board",
    category: "Lumber",
    price: 12.5,
    unit: "item",
    vendor: "Home Depot",
    sku: "HD-DECK-203",
    rating: 4.5,
  },
  {
    id: "L-204",
    name: "Shiplap Pine Board (8ft)",
    category: "Lumber",
    price: 9.75,
    unit: "item",
    vendor: "Lowe's",
    sku: "LW-SHIP-204",
    rating: 4.8,
  },
  {
    id: "L-205",
    name: "Cedar Fence Picket",
    category: "Lumber",
    price: 4.25,
    unit: "item",
    vendor: "Home Depot",
    sku: "HD-CED-205",
    rating: 4.3,
  },

  // Electrical
  {
    id: "E-301",
    name: "Smart Dimmer Switch (WiFi)",
    category: "Electrical",
    price: 29.99,
    unit: "item",
    vendor: "Home Depot",
    sku: "HD-DIM-301",
    rating: 4.3,
  },
  {
    id: "E-302",
    name: "Recessed Lighting Kit (6-pack)",
    category: "Electrical",
    price: 75.0,
    unit: "pack",
    vendor: "Lowe's",
    sku: "LW-LITE-302",
    rating: 4.6,
  },
  {
    id: "E-303",
    name: "12/2 Romex Wire (250ft)",
    category: "Electrical",
    price: 140.0,
    unit: "roll",
    vendor: "Home Depot",
    sku: "HD-WIRE-303",
    rating: 4.8,
  },
  {
    id: "E-304",
    name: "GFCI Outlet (White)",
    category: "Electrical",
    price: 15.0,
    unit: "item",
    vendor: "Lowe's",
    sku: "LW-OUT-304",
    rating: 4.9,
  },
  {
    id: "E-305",
    name: "Ceiling Fan with Light (52 inch)",
    category: "Electrical",
    price: 150.0,
    unit: "item",
    vendor: "Home Depot",
    sku: "HD-FAN-305",
    rating: 4.5,
  },

  // Paint
  {
    id: "PA-401",
    name: "Premium Interior Satin White",
    category: "Paint",
    price: 45.0,
    unit: "gallon",
    vendor: "Home Depot",
    sku: "HD-PNT-401",
    rating: 4.8,
  },
  {
    id: "PA-402",
    name: "Painters Tape (Blue)",
    category: "Paint",
    price: 6.5,
    unit: "roll",
    vendor: "Lowe's",
    sku: "LW-TAPE-402",
    rating: 4.9,
  },
  {
    id: "PA-403",
    name: "9-inch Roller Kit",
    category: "Paint",
    price: 12.99,
    unit: "kit",
    vendor: "Home Depot",
    sku: "HD-ROLL-403",
    rating: 4.4,
  },
  {
    id: "PA-404",
    name: "Exterior Deck Stain (Cedar)",
    category: "Paint",
    price: 38.0,
    unit: "gallon",
    vendor: "Lowe's",
    sku: "LW-STN-404",
    rating: 4.6,
  },
  {
    id: "PA-405",
    name: "Angled Sash Brush (2 inch)",
    category: "Paint",
    price: 9.5,
    unit: "item",
    vendor: "Home Depot",
    sku: "HD-BRSH-405",
    rating: 4.7,
  },

  // Appliances
  {
    id: "A-501",
    name: "Stainless Steel French Door Fridge",
    category: "Appliances",
    price: 1800.0,
    unit: "item",
    vendor: "Best Buy",
    sku: "BB-FRID-501",
    rating: 4.5,
  },
  {
    id: "A-502",
    name: "Gas Range Convection Oven",
    category: "Appliances",
    price: 950.0,
    unit: "item",
    vendor: "Home Depot",
    sku: "HD-RNG-502",
    rating: 4.4,
  },
  {
    id: "A-503",
    name: "Dishwasher with 3rd Rack",
    category: "Appliances",
    price: 650.0,
    unit: "item",
    vendor: "Lowe's",
    sku: "LW-DISH-503",
    rating: 4.3,
  },
  {
    id: "A-504",
    name: "Front Load Washer",
    category: "Appliances",
    price: 800.0,
    unit: "item",
    vendor: "Best Buy",
    sku: "BB-WASH-504",
    rating: 4.7,
  },
  {
    id: "A-505",
    name: "Over-the-Range Microwave",
    category: "Appliances",
    price: 250.0,
    unit: "item",
    vendor: "Home Depot",
    sku: "HD-MIC-505",
    rating: 4.2,
  },

  // Decor
  {
    id: "D-601",
    name: "Round Vanity Mirror (Gold)",
    category: "Decor",
    price: 120.0,
    unit: "item",
    vendor: "Wayfair",
    sku: "WF-MIR-601",
    rating: 4.8,
  },
  {
    id: "D-602",
    name: "Floating Shelf (Walnut)",
    category: "Decor",
    price: 45.0,
    unit: "item",
    vendor: "Lowe's",
    sku: "LW-SHLF-602",
    rating: 4.4,
  },
  {
    id: "D-603",
    name: "Blackout Curtains (Grey)",
    category: "Decor",
    price: 35.0,
    unit: "pair",
    vendor: "Home Depot",
    sku: "HD-CURT-603",
    rating: 4.6,
  },
  {
    id: "D-604",
    name: "Woven Jute Rug (5x7)",
    category: "Decor",
    price: 80.0,
    unit: "item",
    vendor: "Wayfair",
    sku: "WF-RUG-604",
    rating: 4.1,
  },
  {
    id: "D-605",
    name: "Industrial Pipe Towel Bar",
    category: "Decor",
    price: 25.0,
    unit: "item",
    vendor: "Lowe's",
    sku: "LW-BAR-605",
    rating: 4.9,
  },
];
